.TH "esp_rmaker_cmd_ctx_t" 3 "Mon Oct 16 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_cmd_ctx_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBcmd\fP"
.br
.ti -1c
.RI "char \fBreq_id\fP [REQ_ID_LEN]"
.br
.ti -1c
.RI "uint8_t \fBuser_role\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16_t esp_rmaker_cmd_ctx_t::cmd"
Command id 
.SS "char esp_rmaker_cmd_ctx_t::req_id[REQ_ID_LEN]"
Request id 
.SS "uint8_t esp_rmaker_cmd_ctx_t::user_role"
User Role 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
