.TH "esp_rmaker_param_val_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_param_val_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "esp_rmaker_val_type_t \fBtype\fP"
.br
.ti -1c
.RI "\fBesp_rmaker_val_t\fP \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP RainMaker Parameter Value 
.SH "Member Data Documentation"
.PP 
.SS "esp_rmaker_val_type_t esp_rmaker_param_val_t::type"
Type of Value 
.SS "\fBesp_rmaker_val_t\fP esp_rmaker_param_val_t::val"
Actual value\&. Depends on the type 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
