.TH "esp_rmaker_config_t" 3 "Mon Oct 16 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_config_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenable_time_sync\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP RainMaker Configuration 
.SH "Member Data Documentation"
.PP 
.SS "bool esp_rmaker_config_t::enable_time_sync"
Enable Time Sync Setting this true will enable SNTP and fetch the current time before attempting to connect to the ESP RainMaker service 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
