.TH "esp_rmaker_ota_data_t" 3 "Mon Oct 16 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_ota_data_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_ota\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBurl\fP"
.br
.ti -1c
.RI "int \fBfilesize\fP"
.br
.ti -1c
.RI "char * \fBfw_version\fP"
.br
.ti -1c
.RI "char * \fBota_job_id\fP"
.br
.ti -1c
.RI "const char * \fBserver_cert\fP"
.br
.ti -1c
.RI "char * \fBpriv\fP"
.br
.ti -1c
.RI "char * \fBmetadata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OTA Data 
.SH "Member Data Documentation"
.PP 
.SS "int esp_rmaker_ota_data_t::filesize"
Size of the OTA File\&. Can be 0 if the file size isn't received from the ESP RainMaker Cloud 
.SS "char* esp_rmaker_ota_data_t::fw_version"
The firmware version of the OTA image 
.SS "char* esp_rmaker_ota_data_t::metadata"
OTA Metadata\&. Applicable only for OTA using Topics\&. Will be received (if applicable) from the backend, along with the OTA URL 
.SS "char* esp_rmaker_ota_data_t::ota_job_id"
The OTA Job ID received from cloud 
.SS "char* esp_rmaker_ota_data_t::priv"
The private data passed in esp_rmaker_enable_ota() 
.SS "const char* esp_rmaker_ota_data_t::server_cert"
The server certificate passed in esp_rmaker_enable_ota() 
.SS "char* esp_rmaker_ota_data_t::url"
The OTA URL received from ESP RainMaker Cloud 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
