.TH "esp_rmaker_ota_config_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_ota_config_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_ota\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "esp_rmaker_ota_cb_t \fBota_cb\fP"
.br
.ti -1c
.RI "esp_rmaker_post_ota_diag_t \fBota_diag\fP"
.br
.ti -1c
.RI "const char * \fBserver_cert\fP"
.br
.ti -1c
.RI "void * \fBpriv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP RainMaker OTA Configuration 
.SH "Member Data Documentation"
.PP 
.SS "esp_rmaker_ota_cb_t esp_rmaker_ota_config_t::ota_cb"
OTA Callback\&. The callback to be invoked when an OTA Job is available\&. If kept NULL, the internal default callback will be used (Recommended)\&. 
.SS "esp_rmaker_post_ota_diag_t esp_rmaker_ota_config_t::ota_diag"
OTA Diagnostics Callback\&. A post OTA diagnostic handler to be invoked if app rollback feature is enabled\&. If kept NULL, the new firmware will be assumed to be fine, and no rollback will be performed\&. 
.SS "void* esp_rmaker_ota_config_t::priv"
Private Data\&. Optional private data to be passed to the OTA callback\&. 
.SS "const char* esp_rmaker_ota_config_t::server_cert"
Server Certificate\&. The certificate to be passed to the OTA callback for server authentication\&. This is mandatory, unless you have disabled it in ESP HTTPS OTA config option\&. If you are using the ESP RainMaker OTA Service, you can just set this to \fCESP_RMAKER_OTA_DEFAULT_SERVER_CERT\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
