.TH "esp_rmaker_node_info_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_node_info_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBtype\fP"
.br
.ti -1c
.RI "char * \fBfw_version\fP"
.br
.ti -1c
.RI "char * \fBmodel\fP"
.br
.ti -1c
.RI "char * \fBsubtype\fP"
.br
.ti -1c
.RI "char ** \fBsecure_boot_digest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP RainMaker Node information 
.SH "Member Data Documentation"
.PP 
.SS "char* esp_rmaker_node_info_t::fw_version"
Firmware Version (Optional)\&. If not set, PROJECT_VER is used as default (recommended) 
.SS "char* esp_rmaker_node_info_t::model"
Model (Optional)\&. If not set, PROJECT_NAME is used as default (recommended) 
.SS "char* esp_rmaker_node_info_t::name"
Name of the Node 
.SS "char** esp_rmaker_node_info_t::secure_boot_digest"
An array of digests read from efuse\&. Should be freed after use 
.SS "char* esp_rmaker_node_info_t::subtype"
Subtype (Optional)\&. 
.SS "char* esp_rmaker_node_info_t::type"
Type of the Node 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
