.TH "esp_rmaker_val_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_val_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBb\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "char * \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP RainMaker Value 
.SH "Member Data Documentation"
.PP 
.SS "bool esp_rmaker_val_t::b"
Boolean 
.SS "float esp_rmaker_val_t::f"
Float 
.SS "int esp_rmaker_val_t::i"
Integer 
.SS "char* esp_rmaker_val_t::s"
NULL terminated string 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
