.TH "esp_rmaker_system_serv_config_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_system_serv_config_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.ti -1c
.RI "int8_t \fBreboot_seconds\fP"
.br
.ti -1c
.RI "int8_t \fBreset_seconds\fP"
.br
.ti -1c
.RI "int8_t \fBreset_reboot_seconds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
System service configuration 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t esp_rmaker_system_serv_config_t::flags"
Logical OR of system service flags (SYSTEM_SERV_FLAG_REBOOT, SYSTEM_SERV_FLAG_FACTORY_RESET, SYSTEM_SERV_FLAG_WIFI_RESET) as required or SYSTEM_SERV_FLAGS_ALL\&. 
.SS "int8_t esp_rmaker_system_serv_config_t::reboot_seconds"
Time in seconds after which the device should reboot\&. Value of zero would trigger an immediate reboot if a write is received for the Reboot parameter\&. Recommended value: 2 
.SS "int8_t esp_rmaker_system_serv_config_t::reset_reboot_seconds"
Time in seconds after which the device should reboot after it has been reset\&. Value of zero would mean that there won't be any reboot after the reset\&. Recommended value: 2 
.SS "int8_t esp_rmaker_system_serv_config_t::reset_seconds"
Time in seconds after which the device should reset (Wi-Fi or factory)\&. Value of zero would trigger an immediate action if a write is received for the Wi-Fi reset or Factory reset parameter\&. Recommended value: 2 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
