.TH "esp_rmaker_ota_diag_priv_t" 3 "Mon Oct 16 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_ota_diag_priv_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "esp_rmaker_ota_diag_state_t \fBstate\fP"
.br
.ti -1c
.RI "bool \fBrmaker_ota\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool esp_rmaker_ota_diag_priv_t::rmaker_ota"
Flag to indicate whether the OTA which has triggered the Diagnostics checks for rollback was triggered via RainMaker or not\&. This would be useful only when your application has some other mechanism for OTA too\&. 
.SS "esp_rmaker_ota_diag_state_t esp_rmaker_ota_diag_priv_t::state"
OTA diagnostic state 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
