.TH "esp_rmaker_mqtt_config_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_mqtt_config_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_mqtt_glue\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsetup_done\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_get_conn_params_t \fBget_conn_params\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_init_t \fBinit\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_deinit_t \fBdeinit\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_connect_t \fBconnect\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_disconnect_t \fBdisconnect\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_publish_t \fBpublish\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_subscribe_t \fBsubscribe\fP"
.br
.ti -1c
.RI "esp_rmaker_mqtt_unsubscribe_t \fBunsubscribe\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MQTT configuration 
.SH "Member Data Documentation"
.PP 
.SS "esp_rmaker_mqtt_connect_t esp_rmaker_mqtt_config_t::connect"
Pointer to MQTT Connect function\&. 
.SS "esp_rmaker_mqtt_deinit_t esp_rmaker_mqtt_config_t::deinit"
Pointer to MQTT Deinit function\&. 
.SS "esp_rmaker_mqtt_disconnect_t esp_rmaker_mqtt_config_t::disconnect"
Pointer to MQTQ Disconnect function 
.SS "esp_rmaker_mqtt_get_conn_params_t esp_rmaker_mqtt_config_t::get_conn_params"
Pointer to the Get MQTT params function\&. 
.SS "esp_rmaker_mqtt_init_t esp_rmaker_mqtt_config_t::init"
Pointer to MQTT Init function\&. 
.SS "esp_rmaker_mqtt_publish_t esp_rmaker_mqtt_config_t::publish"
Pointer to MQTT Publish function 
.SS "bool esp_rmaker_mqtt_config_t::setup_done"
Flag to indicate if the MQTT config setup is done 
.SS "esp_rmaker_mqtt_subscribe_t esp_rmaker_mqtt_config_t::subscribe"
Pointer to MQTT Subscribe function 
.SS "esp_rmaker_mqtt_unsubscribe_t esp_rmaker_mqtt_config_t::unsubscribe"
Pointer to MQTT Unsubscribe function 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
