.TH "esp_rmaker_write_ctx_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_write_ctx_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "esp_rmaker_req_src_t \fBsrc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Write request Context 
.SH "Member Data Documentation"
.PP 
.SS "esp_rmaker_req_src_t esp_rmaker_write_ctx_t::src"
Source of request 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
