.TH "esp_rmaker_mqtt_conn_params_t" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_mqtt_conn_params_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_rmaker_mqtt_glue\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBmqtt_host\fP"
.br
.ti -1c
.RI "char * \fBclient_id\fP"
.br
.ti -1c
.RI "char * \fBclient_cert\fP"
.br
.ti -1c
.RI "size_t \fBclient_cert_len\fP"
.br
.ti -1c
.RI "char * \fBclient_key\fP"
.br
.ti -1c
.RI "size_t \fBclient_key_len\fP"
.br
.ti -1c
.RI "char * \fBserver_cert\fP"
.br
.ti -1c
.RI "size_t \fBserver_cert_len\fP"
.br
.ti -1c
.RI "void * \fBds_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MQTT Connection parameters 
.SH "Member Data Documentation"
.PP 
.SS "char* esp_rmaker_mqtt_conn_params_t::client_cert"
Client Certificate in DER format or NULL-terminated PEM format 
.SS "size_t esp_rmaker_mqtt_conn_params_t::client_cert_len"
Client Certificate length 
.SS "char* esp_rmaker_mqtt_conn_params_t::client_id"
Client ID 
.SS "char* esp_rmaker_mqtt_conn_params_t::client_key"
Client Key in DER format or NULL-terminated PEM format 
.SS "size_t esp_rmaker_mqtt_conn_params_t::client_key_len"
Client Key length 
.SS "void* esp_rmaker_mqtt_conn_params_t::ds_data"
Pointer for digital signature peripheral context 
.SS "char* esp_rmaker_mqtt_conn_params_t::mqtt_host"
MQTT Host 
.SS "char* esp_rmaker_mqtt_conn_params_t::server_cert"
Server Certificate in DER format or NULL-terminated PEM format 
.SS "size_t esp_rmaker_mqtt_conn_params_t::server_cert_len"
Server Certificate length 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
