.TH "esp_rmaker_time_config" 3 "Tue Oct 17 2023" "ESP RainMaker Programming Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_rmaker_time_config \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBsntp_server_name\fP"
.br
.ti -1c
.RI "sntp_sync_time_cb_t \fBsync_time_cb\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* esp_rmaker_time_config::sntp_server_name"
If not specified, then 'CONFIG_ESP_RMAKER_SNTP_SERVER_NAME' is used as the SNTP server\&. 
.SS "sntp_sync_time_cb_t esp_rmaker_time_config::sync_time_cb"
Optional callback to invoke, whenever time is synchronised\&. This will be called periodically as per the SNTP polling interval (which is 60min by default)\&. If kept NULL, the default callback will be invoked, which will just print the current local time\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP RainMaker Programming Guide from the source code\&.
